[{
  "City": "Bayonne",
  "State": "New Jersey",
  "Link": "//en.wikipedia.org/wiki/Bayonne,_New_Jersey",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Bayonne%2C_New_Jersey.png/180px-Flag_of_Bayonne%2C_New_Jersey.png",
  "Lat": 40.668714,
  "Lon": -74.114309
}, {
  "City": "Newark",
  "State": "New Jersey",
  "Link": "//en.wikipedia.org/wiki/Newark,_New_Jersey",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Newark%2C_New_Jersey.png/180px-Flag_of_Newark%2C_New_Jersey.png",
  "Lat": 40.735657,
  "Lon": -74.172367
}, {
  "City": "Trenton",
  "State": "New Jersey",
  "Link": "//en.wikipedia.org/wiki/Trenton,_New_Jersey",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Flag_of_Trenton%2C_New_Jersey.svg/180px-Flag_of_Trenton%2C_New_Jersey.svg.png",
  "Lat": 40.217053,
  "Lon": -74.742938
}, {
  "City": "Albany",
  "State": "New York",
  "Link": "//en.wikipedia.org/wiki/Albany,_New_York",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Flag_of_Albany%2C_New_York.svg/180px-Flag_of_Albany%2C_New_York.svg.png",
  "Lat": 42.652579,
  "Lon": -73.756232
}, {
  "City": "Buffalo",
  "State": "New York",
  "Link": "//en.wikipedia.org/wiki/Buffalo,_New_York",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Buffalo%2C_New_York.svg/180px-Flag_of_Buffalo%2C_New_York.svg.png",
  "Lat": 42.886447,
  "Lon": -78.878369
}, {
  "City": "Cumberland Head",
  "State": "New York",
  "Link": "//en.wikipedia.org/wiki/Cumberland_Head,_New_York",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Cumberland_Head.svg/180px-Flag_of_Cumberland_Head.svg.png",
  "Lat": 44.716432,
  "Lon": -73.402634
}, {
  "City": "New York City",
  "State": "New York",
  "Link": "//en.wikipedia.org/wiki/New_York_City",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_New_York_City.svg/180px-Flag_of_New_York_City.svg.png",
  "Lat": 40.712784,
  "Lon": -74.005941
}, {
  "City": "Rochester",
  "State": "New York",
  "Link": "//en.wikipedia.org/wiki/Rochester,_New_York",
  "Image": "//upload.wikimedia.org/wikipedia/en/thumb/f/f1/Rochester_NY_city_flag.png/220px-Rochester_NY_city_flag.png",
  "Lat": 43.16103,
  "Lon": -77.610922
}, {
  "City": "Southampton",
  "State": "New York",
  "Link": "//en.wikipedia.org/wiki/Southampton,_New_York",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Flag_of_Southampton%2C_New_York.png/180px-Flag_of_Southampton%2C_New_York.png",
  "Lat": 40.884267,
  "Lon": -72.38953
}, {
  "City": "Washington",
  "State": "New York",
  "Link": "//en.wikipedia.org/wiki/Washington,_New_York",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_Washington%2C_New_York.png/180px-Flag_of_Washington%2C_New_York.png",
  "Lat": 41.78666,
  "Lon": -73.681389
}, {
  "City": "Yonkers",
  "State": "New York",
  "Link": "//en.wikipedia.org/wiki/Yonkers,_New_York",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Yonkers%2C_New_York.svg/180px-Flag_of_Yonkers%2C_New_York.svg.png",
  "Lat": 40.93121,
  "Lon": -73.898747
}, {
  "City": "Easton",
  "State": "Pennsylvania",
  "Link": "//en.wikipedia.org/wiki/Easton,_Pennsylvania",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Easton%2C_Pennsylvania.svg/180px-Flag_of_Easton%2C_Pennsylvania.svg.png",
  "Lat": 40.688432,
  "Lon": -75.220732
}, {
  "City": "Erie",
  "State": "Pennsylvania",
  "Link": "//en.wikipedia.org/wiki/Erie,_Pennsylvania",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Erie%2C_Pennsylvania.svg/180px-Flag_of_Erie%2C_Pennsylvania.svg.png",
  "Lat": 42.129224,
  "Lon": -80.085059
}, {
  "City": "Lancaster",
  "State": "Pennsylvania",
  "Link": "//en.wikipedia.org/wiki/Lancaster,_Pennsylvania",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Flag_of_Lancaster%2C_Pennsylvania.svg/180px-Flag_of_Lancaster%2C_Pennsylvania.svg.png",
  "Lat": 40.037876,
  "Lon": -76.305514
}, {
  "City": "Philadelphia",
  "State": "Pennsylvania",
  "Link": "//en.wikipedia.org/wiki/Philadelphia",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Flag_of_Philadelphia%2C_Pennsylvania.svg/180px-Flag_of_Philadelphia%2C_Pennsylvania.svg.png",
  "Lat": 39.952584,
  "Lon": -75.165222
}, {
  "City": "Pittsburgh",
  "State": "Pennsylvania",
  "Link": "//en.wikipedia.org/wiki/Pittsburgh",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Pittsburgh%2C_Pennsylvania.svg/180px-Flag_of_Pittsburgh%2C_Pennsylvania.svg.png",
  "Lat": 40.440625,
  "Lon": -79.995886
}, {
  "City": "Bridgeport",
  "State": "Connecticut",
  "Link": "//en.wikipedia.org/wiki/Bridgeport,_Connecticut",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Bridgeport_flag.png/180px-Bridgeport_flag.png",
  "Lat": 41.186548,
  "Lon": -73.195177
}, {
  "City": "Madawaska",
  "State": "Maine",
  "Link": "//en.wikipedia.org/wiki/Madawaska,_Maine",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Acadia.svg/180px-Flag_of_Acadia.svg.png",
  "Lat": 47.355315,
  "Lon": -68.321703
}, {
  "City": "Greenbush",
  "State": "Maine",
  "Link": "//en.wikipedia.org/wiki/Greenbush,_Maine",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Greenbush%2C_Maine.png/180px-Flag_of_Greenbush%2C_Maine.png",
  "Lat": 45.080341,
  "Lon": -68.650864
}, {
  "City": "Lincoln",
  "State": "Maine",
  "Link": "//en.wikipedia.org/wiki/Lincoln,_Maine",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Lincoln%2C_Maine.png/180px-Flag_of_Lincoln%2C_Maine.png",
  "Lat": 45.36223,
  "Lon": -68.505001
}, {
  "City": "North Yarmouth",
  "State": "Maine",
  "Link": "//en.wikipedia.org/wiki/North_Yarmouth,_Maine",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_North_Yarmouth%2C_Maine.png/180px-Flag_of_North_Yarmouth%2C_Maine.png",
  "Lat": 43.85735,
  "Lon": -70.238871
}, {
  "City": "Washington",
  "State": "Maine",
  "Link": "//en.wikipedia.org/wiki/Washington,_Maine",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Flag_of_Washington%2C_Maine.png/180px-Flag_of_Washington%2C_Maine.png",
  "Lat": 44.273558,
  "Lon": -69.367658
}, {
  "City": "Boston",
  "State": "Massachusetts",
  "Link": "//en.wikipedia.org/wiki/Boston",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Boston.svg/180px-Flag_of_Boston.svg.png",
  "Lat": 42.358487,
  "Lon": -71.060097
}, {
  "City": "Bridgewater",
  "State": "Massachusetts",
  "Link": "//en.wikipedia.org/wiki/Bridgewater,_Massachusetts",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Flag_of_Bridgewater%2C_Massachusetts.svg/180px-Flag_of_Bridgewater%2C_Massachusetts.svg.png",
  "Lat": 41.990352,
  "Lon": -70.975054
}, {
  "City": "Nantucket",
  "State": "Massachusetts",
  "Link": "//en.wikipedia.org/wiki/Nantucket",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Nantucket-Flag.gif/180px-Nantucket-Flag.gif",
  "Lat": 41.28347,
  "Lon": -70.099451
}, {
  "City": "Taunton",
  "State": "Massachusetts",
  "Link": "//en.wikipedia.org/wiki/Taunton,_Massachusetts",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Taunton%2C_Massachusetts.svg/180px-Flag_of_Taunton%2C_Massachusetts.svg.png",
  "Lat": 41.900101,
  "Lon": -71.089767
}, {
  "City": "Worcester",
  "State": "Massachusetts",
  "Link": "//en.wikipedia.org/wiki/Worcester,_Massachusetts",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Flag_of_Worcester%2C_Massachusetts.svg/180px-Flag_of_Worcester%2C_Massachusetts.svg.png",
  "Lat": 42.262593,
  "Lon": -71.802293
}, {
  "City": "Wilmington",
  "State": "Delaware",
  "Link": "//en.wikipedia.org/wiki/Wilmington,_Delaware",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/b2/WilmingtonDEflag.gif/180px-WilmingtonDEflag.gif",
  "Lat": 39.739072,
  "Lon": -75.539788
}, {
  "City": "Apopka",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Apopka,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Apopka%2C_Florida.png/180px-Flag_of_Apopka%2C_Florida.png",
  "Lat": 28.676111,
  "Lon": -81.510556
}, {
  "City": "Coconut Creek",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Coconut_Creek,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_Coconut_Creek%2C_Florida.png/180px-Flag_of_Coconut_Creek%2C_Florida.png",
  "Lat": 26.251748,
  "Lon": -80.178935
}, {
  "City": "Coral Springs",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Coral_Springs,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Coral_Springs%2C_Florida.png/180px-Flag_of_Coral_Springs%2C_Florida.png",
  "Lat": 26.271192,
  "Lon": -80.270604
}, {
  "City": "Coral Gables",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Coral_Gables,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/5/54/Flag_of_Coral_Gables%2C_Florida.png/180px-Flag_of_Coral_Gables%2C_Florida.png",
  "Lat": 25.72149,
  "Lon": -80.268384
}, {
  "City": "Fort Lauderdale",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Fort_Lauderdale,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Fort_Lauderdale%2C_Florida.png/180px-Flag_of_Fort_Lauderdale%2C_Florida.png",
  "Lat": 26.122439,
  "Lon": -80.137317
}, {
  "City": "Fort Walton Beach",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Fort_Walton_Beach,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Fort_Walton_Beach%2C_Florida.png/180px-Flag_of_Fort_Walton_Beach%2C_Florida.png",
  "Lat": 30.420071,
  "Lon": -86.617031
}, {
  "City": "Gainesville",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Gainesville,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Gainesville%2C_Florida.png/180px-Flag_of_Gainesville%2C_Florida.png",
  "Lat": 29.651634,
  "Lon": -82.324826
}, {
  "City": "Hialeah",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Hialeah,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Flag_of_Hialeah%2C_Florida.png/180px-Flag_of_Hialeah%2C_Florida.png",
  "Lat": 25.857596,
  "Lon": -80.278106
}, {
  "City": "Hollywood",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Hollywood,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Hollywood%2C_Florida.png/180px-Flag_of_Hollywood%2C_Florida.png",
  "Lat": 26.011201,
  "Lon": -80.14949
}, {
  "City": "Jacksonville",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Jacksonville,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Jacksonville%2C_Florida.svg/180px-Flag_of_Jacksonville%2C_Florida.svg.png",
  "Lat": 30.332184,
  "Lon": -81.655651
}, {
  "City": "Key West",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Key_West,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Key_West%2C_Florida.svg/180px-Flag_of_Key_West%2C_Florida.svg.png",
  "Lat": 24.555059,
  "Lon": -81.779987
}, {
  "City": "Kissimmee",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Kissimmee,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/5/52/Flag_of_Kissimmee%2C_Florida.png/180px-Flag_of_Kissimmee%2C_Florida.png",
  "Lat": 28.291956,
  "Lon": -81.407571
}, {
  "City": "Lantana",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Lantana,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Flag_of_Lantana%2C_Florida.png/180px-Flag_of_Lantana%2C_Florida.png",
  "Lat": 26.586736,
  "Lon": -80.051986
}, {
  "City": "Lauderdale Lakes",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Lauderdale_Lakes,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_Lauderdale_Lakes%2C_Florida.png/180px-Flag_of_Lauderdale_Lakes%2C_Florida.png",
  "Lat": 26.166474,
  "Lon": -80.208381
}, {
  "City": "Lauderhill",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Lauderhill,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Lauderhill%2C_Florida.png/180px-Flag_of_Lauderhill%2C_Florida.png",
  "Lat": 26.140364,
  "Lon": -80.213381
}, {
  "City": "Miami",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Miami",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Miami%2C_Florida.svg/180px-Flag_of_Miami%2C_Florida.svg.png",
  "Lat": 25.76168,
  "Lon": -80.19179
}, {
  "City": "Oakland Park",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Oakland_Park,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Oakland_Park%2C_Florida.png/180px-Flag_of_Oakland_Park%2C_Florida.png",
  "Lat": 26.172307,
  "Lon": -80.131989
}, {
  "City": "Orlando",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Orlando,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Orlando%2C_Florida.png/180px-Flag_of_Orlando%2C_Florida.png",
  "Lat": 28.538336,
  "Lon": -81.379236
}, {
  "City": "Panama City",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Panama_City,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_Panama_City%2C_Florida.png/180px-Flag_of_Panama_City%2C_Florida.png",
  "Lat": 30.158813,
  "Lon": -85.660206
}, {
  "City": "Pensacola",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Pensacola,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Flag_of_Pensacola.svg/180px-Flag_of_Pensacola.svg.png",
  "Lat": 30.421309,
  "Lon": -87.216915
}, {
  "City": "Sarasota",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Sarasota,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Sarasota%2C_Florida.png/180px-Flag_of_Sarasota%2C_Florida.png",
  "Lat": 27.336435,
  "Lon": -82.530653
}, {
  "City": "St. Petersburg",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/St._Petersburg,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_St._Petersburg%2C_Florida.png/180px-Flag_of_St._Petersburg%2C_Florida.png",
  "Lat": 27.773056,
  "Lon": -82.64
}, {
  "City": "Tallahassee",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Tallahassee,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_Tallahassee%2C_Florida.png/180px-Flag_of_Tallahassee%2C_Florida.png",
  "Lat": 30.438256,
  "Lon": -84.280733
}, {
  "City": "Tamarac",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Tamarac,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Tamarac%2C_Florida.png/180px-Flag_of_Tamarac%2C_Florida.png",
  "Lat": 26.212861,
  "Lon": -80.249771
}, {
  "City": "Tampa",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Tampa,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_Tampa%2C_Florida.svg/180px-Flag_of_Tampa%2C_Florida.svg.png",
  "Lat": 27.950575,
  "Lon": -82.457178
}, {
  "City": "West Melbourne",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/West_Melbourne,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_West_Melbourne%2C_Florida.png/180px-Flag_of_West_Melbourne%2C_Florida.png",
  "Lat": 28.071683,
  "Lon": -80.653388
}, {
  "City": "Winter Park",
  "State": "Florida",
  "Link": "//en.wikipedia.org/wiki/Winter_Park,_Florida",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Winter_Park%2C_Florida.png/180px-Flag_of_Winter_Park%2C_Florida.png",
  "Lat": 28.6,
  "Lon": -81.339235
}, {
  "City": "Atlanta",
  "State": "Georgia",
  "Link": "//en.wikipedia.org/wiki/Atlanta",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Atlanta.svg/180px-Flag_of_Atlanta.svg.png",
  "Lat": 33.748995,
  "Lon": -84.387982
}, {
  "City": "Savannah",
  "State": "Georgia",
  "Link": "//en.wikipedia.org/wiki/Savannah,_Georgia",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Savannah%2C_Georgia.png/180px-Flag_of_Savannah%2C_Georgia.png",
  "Lat": 32.083541,
  "Lon": -81.099834
}, {
  "City": "Trenton",
  "State": "Georgia",
  "Link": "//en.wikipedia.org/wiki/Trenton,_Georgia",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_the_State_of_Georgia_%281956-2001%29.svg/180px-Flag_of_the_State_of_Georgia_%281956-2001%29.svg.png",
  "Lat": 34.872022,
  "Lon": -85.50913
}, {
  "City": "Annapolis",
  "State": "Maryland",
  "Link": "//en.wikipedia.org/wiki/Annapolis",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Annapolis%2C_Maryland.png/180px-Flag_of_Annapolis%2C_Maryland.png",
  "Lat": 38.978445,
  "Lon": -76.492183
}, {
  "City": "Baltimore",
  "State": "Maryland",
  "Link": "//en.wikipedia.org/wiki/Baltimore",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Baltimore%2C_Maryland.svg/180px-Flag_of_Baltimore%2C_Maryland.svg.png",
  "Lat": 39.290385,
  "Lon": -76.612189
}, {
  "City": "College Park",
  "State": "Maryland",
  "Link": "//en.wikipedia.org/wiki/College_Park,_Maryland",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Flag_of_College_Park%2C_Maryland.png/180px-Flag_of_College_Park%2C_Maryland.png",
  "Lat": 38.989697,
  "Lon": -76.93776
}, {
  "City": "Greenbelt",
  "State": "Maryland",
  "Link": "//en.wikipedia.org/wiki/Greenbelt,_Maryland",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Greenbelt%2C_Maryland.svg/180px-Flag_of_Greenbelt%2C_Maryland.svg.png",
  "Lat": 39.004554,
  "Lon": -76.875528
}, {
  "City": "Hyattsville",
  "State": "Maryland",
  "Link": "//en.wikipedia.org/wiki/Hyattsville,_Maryland",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Hyattsville%2C_Maryland.png/180px-Flag_of_Hyattsville%2C_Maryland.png",
  "Lat": 38.955944,
  "Lon": -76.94553
}, {
  "City": "Montgomery Village",
  "State": "Maryland",
  "Link": "//en.wikipedia.org/wiki/Montgomery_Village,_Maryland",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_Montgomery_Village%2C_Maryland.svg/180px-Flag_of_Montgomery_Village%2C_Maryland.svg.png",
  "Lat": 39.172728,
  "Lon": -77.203604
}, {
  "City": "Ocean City",
  "State": "Maryland",
  "Link": "//en.wikipedia.org/wiki/Ocean_City,_Maryland",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Flag_of_Ocean_City.svg/180px-Flag_of_Ocean_City.svg.png",
  "Lat": 38.336503,
  "Lon": -75.084906
}, {
  "City": "Rockville",
  "State": "Maryland",
  "Link": "//en.wikipedia.org/wiki/Rockville,_Maryland",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Rockville%2C_Maryland.svg/180px-Flag_of_Rockville%2C_Maryland.svg.png",
  "Lat": 39.083997,
  "Lon": -77.152758
}, {
  "City": "Durham",
  "State": "North Carolina",
  "Link": "//en.wikipedia.org/wiki/Durham,_North_Carolina",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Durham%2C_North_Carolina.svg/145px-Flag_of_Durham%2C_North_Carolina.svg.png",
  "Lat": 35.994033,
  "Lon": -78.898619
}, {
  "City": "Raleigh",
  "State": "North Carolina",
  "Link": "//en.wikipedia.org/wiki/Raleigh,_North_Carolina",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Raleigh.svg/180px-Flag_of_Raleigh.svg.png",
  "Lat": 35.77959,
  "Lon": -78.638179
}, {
  "City": "Charleston",
  "State": "South Carolina",
  "Link": "//en.wikipedia.org/wiki/Charleston,_South_Carolina",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Charleston%2C_South_Carolina.svg/180px-Flag_of_Charleston%2C_South_Carolina.svg.png",
  "Lat": 32.776475,
  "Lon": -79.931051
}, {
  "City": "Hampton Roads",
  "State": "Virginia",
  "Link": "//en.wikipedia.org/wiki/Hampton_Roads",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Hampton_Roads%2C_Virginia.svg/180px-Flag_of_Hampton_Roads%2C_Virginia.svg.png",
  "Lat": 36.966667,
  "Lon": -76.366667
}, {
  "City": "Minnieville",
  "State": "Virginia",
  "Link": "//en.wikipedia.org/wiki/Minnieville,_Virginia",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Minnieville_Flag.png/180px-Minnieville_Flag.png",
  "Lat": 38.636505,
  "Lon": -77.352592
}, {
  "City": "Richmond",
  "State": "Virginia",
  "Link": "//en.wikipedia.org/wiki/Richmond,_Virginia",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Richmond%2C_Virginia.svg/180px-Flag_of_Richmond%2C_Virginia.svg.png",
  "Lat": 37.540725,
  "Lon": -77.436048
}, {
  "City": "Tangier Island",
  "State": "Virginia",
  "Link": "//en.wikipedia.org/wiki/Tangier_Island,_Virginia",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Tangier_Island%2C_Virginia.png/180px-Flag_of_Tangier_Island%2C_Virginia.png",
  "Lat": 37.825065,
  "Lon": -75.997662
}, {
  "City": "Virginia Beach",
  "State": "Virginia",
  "Link": "//en.wikipedia.org/wiki/Virginia_Beach,_Virginia",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Flag_of_Virginia_Beach%2C_Virginia.png/180px-Flag_of_Virginia_Beach%2C_Virginia.png",
  "Lat": 36.852926,
  "Lon": -75.977985
}, {
  "City": "Washington",
  "State": "D.C.",
  "Link": "//en.wikipedia.org/wiki/Washington,_D.C.",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_Washington%2C_D.C..svg/180px-Flag_of_Washington%2C_D.C..svg.png",
  "Lat": 38.907192,
  "Lon": -77.036871
}, {
  "City": "Huntington",
  "State": "West Virginia",
  "Link": "//en.wikipedia.org/wiki/Huntington,_West_Virginia",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/0/09/City_flag_of_Huntington%2C_WV.jpg/180px-City_flag_of_Huntington%2C_WV.jpg",
  "Lat": 38.41925,
  "Lon": -82.445154
}, {
  "City": "Chicago",
  "State": "Illinois",
  "Link": "//en.wikipedia.org/wiki/Chicago",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Chicago%2C_Illinois.svg/180px-Flag_of_Chicago%2C_Illinois.svg.png",
  "Lat": 41.878114,
  "Lon": -87.629798
}, {
  "City": "Springfield",
  "State": "Illinois",
  "Link": "//en.wikipedia.org/wiki/Springfield,_Illinois",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Springfield%2C_Illinois.svg/180px-Flag_of_Springfield%2C_Illinois.svg.png",
  "Lat": 39.781721,
  "Lon": -89.650148
}, {
  "City": "Evansville",
  "State": "Indiana",
  "Link": "//en.wikipedia.org/wiki/Evansville,_Indiana",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Flag_of_Evansville%2C_Indiana.svg/180px-Flag_of_Evansville%2C_Indiana.svg.png",
  "Lat": 37.971559,
  "Lon": -87.57109
}, {
  "City": "Fort Wayne",
  "State": "Indiana",
  "Link": "//en.wikipedia.org/wiki/Fort_Wayne,_Indiana",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_Fort_Wayne%2C_Indiana.svg/180px-Flag_of_Fort_Wayne%2C_Indiana.svg.png",
  "Lat": 41.079273,
  "Lon": -85.139351
}, {
  "City": "Indianapolis",
  "State": "Indiana",
  "Link": "//en.wikipedia.org/wiki/Indianapolis",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Indianapolis.svg/180px-Flag_of_Indianapolis.svg.png",
  "Lat": 39.768403,
  "Lon": -86.158068
}, {
  "City": "Lafayette",
  "State": "Indiana",
  "Link": "//en.wikipedia.org/wiki/Lafayette,_Indiana",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_Lafayette%2C_Indiana.svg/180px-Flag_of_Lafayette%2C_Indiana.svg.png",
  "Lat": 40.416702,
  "Lon": -86.875287
}, {
  "City": "Vincennes",
  "State": "Indiana",
  "Link": "//en.wikipedia.org/wiki/Vincennes,_Indiana",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/2/28/VincennesFlag.png/180px-VincennesFlag.png",
  "Lat": 38.677269,
  "Lon": -87.528633
}, {
  "City": "Detroit",
  "State": "Michigan",
  "Link": "//en.wikipedia.org/wiki/Detroit",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/1/14/Flag_of_Detroit%2C_Michigan.svg/180px-Flag_of_Detroit%2C_Michigan.svg.png",
  "Lat": 42.331427,
  "Lon": -83.045754
}, {
  "City": "Cincinnati",
  "State": "Ohio",
  "Link": "//en.wikipedia.org/wiki/Cincinnati",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Cincinnati%2C_Ohio.svg/180px-Flag_of_Cincinnati%2C_Ohio.svg.png",
  "Lat": 39.103118,
  "Lon": -84.51202
}, {
  "City": "Cleveland",
  "State": "Ohio",
  "Link": "//en.wikipedia.org/wiki/Cleveland",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Cleveland%2C_Ohio.svg/180px-Flag_of_Cleveland%2C_Ohio.svg.png",
  "Lat": 41.49932,
  "Lon": -81.694361
}, {
  "City": "Columbus",
  "State": "Ohio",
  "Link": "//en.wikipedia.org/wiki/Columbus,_Ohio",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Flag_of_Columbus%2C_Ohio.svg/180px-Flag_of_Columbus%2C_Ohio.svg.png",
  "Lat": 39.961176,
  "Lon": -82.998794
}, {
  "City": "Toledo",
  "State": "Ohio",
  "Link": "//en.wikipedia.org/wiki/Toledo,_Ohio",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Flag_of_Toledo%2C_Ohio.svg/180px-Flag_of_Toledo%2C_Ohio.svg.png",
  "Lat": 41.663938,
  "Lon": -83.555212
}, {
  "City": "Madison",
  "State": "Wisconsin",
  "Link": "//en.wikipedia.org/wiki/Madison,_Wisconsin",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Madison%2C_Wisconsin.svg/180px-Flag_of_Madison%2C_Wisconsin.svg.png",
  "Lat": 43.073052,
  "Lon": -89.40123
}, {
  "City": "Milwaukee",
  "State": "Wisconsin",
  "Link": "//en.wikipedia.org/wiki/Milwaukee",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Milwaukee%2C_Wisconsin.svg/180px-Flag_of_Milwaukee%2C_Wisconsin.svg.png",
  "Lat": 43.038903,
  "Lon": -87.906474
}, {
  "City": "Birmingham",
  "State": "Alabama",
  "Link": "//en.wikipedia.org/wiki/Birmingham,_Alabama",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/76/Flag_of_Birmingham%2C_Alabama.svg/180px-Flag_of_Birmingham%2C_Alabama.svg.png",
  "Lat": 33.520661,
  "Lon": -86.80249
}, {
  "City": "Mobile",
  "State": "Alabama",
  "Link": "//en.wikipedia.org/wiki/Mobile,_Alabama",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Mobile%2C_Alabama.png/180px-Flag_of_Mobile%2C_Alabama.png",
  "Lat": 30.695366,
  "Lon": -88.039891
}, {
  "City": "Montgomery",
  "State": "Alabama",
  "Link": "//en.wikipedia.org/wiki/Montgomery,_Alabama",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Flag_of_Montgomery%2C_Alabama.svg/180px-Flag_of_Montgomery%2C_Alabama.svg.png",
  "Lat": 32.366805,
  "Lon": -86.299969
}, {
  "City": "Louisville",
  "State": "Kentucky",
  "Link": "//en.wikipedia.org/wiki/Louisville,_Kentucky",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_placeholder.svg/180px-Flag_placeholder.svg.png",
  "Lat": 38.252665,
  "Lon": -85.758456
}, {
  "City": "Jackson",
  "State": "Mississippi",
  "Link": "//en.wikipedia.org/wiki/Jackson,_Mississippi",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_Jackson%2C_Mississippi.svg/180px-Flag_of_Jackson%2C_Mississippi.svg.png",
  "Lat": 32.298757,
  "Lon": -90.18481
}, {
  "City": "Pass Christian",
  "State": "Mississippi",
  "Link": "//en.wikipedia.org/wiki/Pass_Christian,_Mississippi",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/4/46/Friendship_flag.png/180px-Friendship_flag.png",
  "Lat": 30.315753,
  "Lon": -89.247543
}, {
  "City": "Chattanooga",
  "State": "Tennessee",
  "Link": "//en.wikipedia.org/wiki/Chattanooga,_Tennessee",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/2/22/Flag_of_Chattanooga.svg/180px-Flag_of_Chattanooga.svg.png",
  "Lat": 35.04563,
  "Lon": -85.30968
}, {
  "City": "Memphis",
  "State": "Tennessee",
  "Link": "//en.wikipedia.org/wiki/Memphis,_Tennessee",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Flag_of_Memphis%2C_Tennessee.svg/180px-Flag_of_Memphis%2C_Tennessee.svg.png",
  "Lat": 35.149534,
  "Lon": -90.04898
}, {
  "City": "Nashville",
  "State": "Tennessee",
  "Link": "//en.wikipedia.org/wiki/Nashville,_Tennessee",
  "Image": "//upload.wikimedia.org/wikipedia/en/thumb/2/20/Nashville_flag.png/220px-Nashville_flag.png",
  "Lat": 36.162664,
  "Lon": -86.781602
}, {
  "City": "Des Moines",
  "State": "Iowa",
  "Link": "//en.wikipedia.org/wiki/Des_Moines,_Iowa",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Des_Moines%2C_Iowa.svg/180px-Flag_of_Des_Moines%2C_Iowa.svg.png",
  "Lat": 41.600545,
  "Lon": -93.609106
}, {
  "City": "Red Oak",
  "State": "Iowa",
  "Link": "//en.wikipedia.org/wiki/Red_Oak,_Iowa",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Red_Oak%2C_Iowa.svg/180px-Flag_of_Red_Oak%2C_Iowa.svg.png",
  "Lat": 41.011667,
  "Lon": -95.227222
}, {
  "City": "Topeka",
  "State": "Kansas",
  "Link": "//en.wikipedia.org/wiki/Topeka,_Kansas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Topeka%2C_Kansas.png/180px-Flag_of_Topeka%2C_Kansas.png",
  "Lat": 39.055824,
  "Lon": -95.689018
}, {
  "City": "Wichita",
  "State": "Kansas",
  "Link": "//en.wikipedia.org/wiki/Wichita,_Kansas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Wichita%2C_Kansas.svg/180px-Flag_of_Wichita%2C_Kansas.svg.png",
  "Lat": 37.688889,
  "Lon": -97.336111
}, {
  "City": "Brooklyn Park",
  "State": "Minnesota",
  "Link": "//en.wikipedia.org/wiki/Brooklyn_Park,_Minnesota",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Brooklyn_Park%2C_Minnesota.svg/180px-Flag_of_Brooklyn_Park%2C_Minnesota.svg.png",
  "Lat": 45.094132,
  "Lon": -93.35634
}, {
  "City": "Duluth",
  "State": "Minnesota",
  "Link": "//en.wikipedia.org/wiki/Duluth,_Minnesota",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Duluth_Flag.jpg/180px-Duluth_Flag.jpg",
  "Lat": 46.786672,
  "Lon": -92.100485
}, {
  "City": "Eagan",
  "State": "Minnesota",
  "Link": "//en.wikipedia.org/wiki/Eagan,_Minnesota",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Eagan%2C_Minnesota.svg/180px-Flag_of_Eagan%2C_Minnesota.svg.png",
  "Lat": 44.804132,
  "Lon": -93.166886
}, {
  "City": "Faribault",
  "State": "Minnesota",
  "Link": "//en.wikipedia.org/wiki/Faribault,_Minnesota",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Faribault%2C_Minnesota.png/180px-Flag_of_Faribault%2C_Minnesota.png",
  "Lat": 44.294964,
  "Lon": -93.268827
}, {
  "City": "Little Canada",
  "State": "Minnesota",
  "Link": "//en.wikipedia.org/wiki/Little_Canada,_Minnesota",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Little_Canada%2C_Minnesota.svg/180px-Flag_of_Little_Canada%2C_Minnesota.svg.png",
  "Lat": 45.02691,
  "Lon": -93.08772
}, {
  "City": "Minneapolis",
  "State": "Minnesota",
  "Link": "//en.wikipedia.org/wiki/Minneapolis,_Minnesota",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Minneapolis%2C_Minnesota.svg/180px-Flag_of_Minneapolis%2C_Minnesota.svg.png",
  "Lat": 44.976154,
  "Lon": -93.267431
}, {
  "City": "Prior Lake",
  "State": "Minnesota",
  "Link": "//en.wikipedia.org/wiki/Prior_Lake,_Minnesota",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Flag_of_Prior_Lake%2C_Minnesota.svg/180px-Flag_of_Prior_Lake%2C_Minnesota.svg.png",
  "Lat": 44.713297,
  "Lon": -93.422727
}, {
  "City": "Rochester",
  "State": "Minnesota",
  "Link": "//en.wikipedia.org/wiki/Rochester,_Minnesota",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Rochester%2C_Minnesota.svg/180px-Flag_of_Rochester%2C_Minnesota.svg.png",
  "Lat": 44.0234,
  "Lon": -92.46295
}, {
  "City": "Saint Paul",
  "State": "Minnesota",
  "Link": "//en.wikipedia.org/wiki/Saint_Paul,_Minnesota",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Flag_of_St._Paul%2C_Minnesota.svg/180px-Flag_of_St._Paul%2C_Minnesota.svg.png",
  "Lat": 44.953703,
  "Lon": -93.089958
}, {
  "City": "Woodbury",
  "State": "Minnesota",
  "Link": "//en.wikipedia.org/wiki/Woodbury,_Minnesota",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_Woodbury%2C_Minnesota.png/180px-Flag_of_Woodbury%2C_Minnesota.png",
  "Lat": 44.923855,
  "Lon": -92.95938
}, {
  "City": "Jefferson City",
  "State": "Missouri",
  "Link": "//en.wikipedia.org/wiki/Jefferson_City,_Missouri",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_Jefferson_City%2C_Missouri.svg/180px-Flag_of_Jefferson_City%2C_Missouri.svg.png",
  "Lat": 38.576702,
  "Lon": -92.173516
}, {
  "City": "Kansas City",
  "State": "Missouri",
  "Link": "//en.wikipedia.org/wiki/Kansas_City,_Missouri",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kansas_City%2C_Missouri.svg/180px-Flag_of_Kansas_City%2C_Missouri.svg.png",
  "Lat": 39.099727,
  "Lon": -94.578567
}, {
  "City": "St. Louis",
  "State": "Missouri",
  "Link": "//en.wikipedia.org/wiki/St._Louis,_Missouri",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_St._Louis%2C_Missouri.svg/180px-Flag_of_St._Louis%2C_Missouri.svg.png",
  "Lat": 38.627003,
  "Lon": -90.199404
}, {
  "City": "Little Rock",
  "State": "Arkansas",
  "Link": "//en.wikipedia.org/wiki/Little_Rock,_Arkansas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Little_Rock.svg/180px-Flag_of_Little_Rock.svg.png",
  "Lat": 34.746481,
  "Lon": -92.289595
}, {
  "City": "Baton Rouge",
  "State": "Louisiana",
  "Link": "//en.wikipedia.org/wiki/Baton_Rouge,_Louisiana",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Flag_of_Baton_Rouge.svg/180px-Flag_of_Baton_Rouge.svg.png",
  "Lat": 30.458283,
  "Lon": -91.14032
}, {
  "City": "New Orleans",
  "State": "Louisiana",
  "Link": "//en.wikipedia.org/wiki/New_Orleans",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_New_Orleans%2C_Louisiana.svg/180px-Flag_of_New_Orleans%2C_Louisiana.svg.png",
  "Lat": 29.951066,
  "Lon": -90.071532
}, {
  "City": "Shreveport",
  "State": "Louisiana",
  "Link": "//en.wikipedia.org/wiki/Shreveport",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/68/Shreveport-City-Flag.png/180px-Shreveport-City-Flag.png",
  "Lat": 32.525152,
  "Lon": -93.750179
}, {
  "City": "Holdenville",
  "State": "Oklahoma",
  "Link": "//en.wikipedia.org/wiki/Holdenville,_Oklahoma",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/8/80/Flag_of_Holdenville.png/180px-Flag_of_Holdenville.png",
  "Lat": 35.080362,
  "Lon": -96.399177
}, {
  "City": "Abilene",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Abilene,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Flag_of_Abilene%2C_Texas.PNG/180px-Flag_of_Abilene%2C_Texas.PNG",
  "Lat": 32.448736,
  "Lon": -99.733144
}, {
  "City": "Allen",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Allen,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Flag_of_Allen%2C_Texas.png/180px-Flag_of_Allen%2C_Texas.png",
  "Lat": 33.103174,
  "Lon": -96.67055
}, {
  "City": "Benbrook",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Benbrook,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Benbrook%2C_Texas.svg/180px-Flag_of_Benbrook%2C_Texas.svg.png",
  "Lat": 32.673188,
  "Lon": -97.460576
}, {
  "City": "Carrollton",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Carrollton,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Carrollton%2C_Texas.svg/180px-Flag_of_Carrollton%2C_Texas.svg.png",
  "Lat": 32.975642,
  "Lon": -96.889964
}, {
  "City": "Corpus Christi",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Corpus_Christi,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Corpus_Christi%2C_Texas.svg/180px-Flag_of_Corpus_Christi%2C_Texas.svg.png",
  "Lat": 27.800583,
  "Lon": -97.396381
}, {
  "City": "Dallas",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Dallas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Dallas.svg/180px-Flag_of_Dallas.svg.png",
  "Lat": 32.780262,
  "Lon": -96.800978
}, {
  "City": "Denison",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Denison,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_Denison%2C_Texas.svg/180px-Flag_of_Denison%2C_Texas.svg.png",
  "Lat": 33.755659,
  "Lon": -96.536658
}, {
  "City": "DeSoto",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/DeSoto,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/en/thumb/2/26/Flag_of_DeSoto%2C_Texas.png/180px-Flag_of_DeSoto%2C_Texas.png",
  "Lat": 32.5897,
  "Lon": -96.857074
}, {
  "City": "El Paso",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/El_Paso,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_El_Paso%2C_Texas.svg/180px-Flag_of_El_Paso%2C_Texas.svg.png",
  "Lat": 31.777576,
  "Lon": -106.442456
}, {
  "City": "Harlingen",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Harlingen,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Flag_of_Harlingen%2C_Texas.PNG/180px-Flag_of_Harlingen%2C_Texas.PNG",
  "Lat": 26.190631,
  "Lon": -97.696103
}, {
  "City": "Harker Heights",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Harker_Heights,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Harker_Heights%2C_Texas.png/180px-Flag_of_Harker_Heights%2C_Texas.png",
  "Lat": 31.08351,
  "Lon": -97.659738
}, {
  "City": "Houston",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Houston",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Flag_of_Houston%2C_Texas.svg/180px-Flag_of_Houston%2C_Texas.svg.png",
  "Lat": 29.760427,
  "Lon": -95.369803
}, {
  "City": "Irving",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Irving,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/61/Flag_of_Irving%2C_Texas.svg/180px-Flag_of_Irving%2C_Texas.svg.png",
  "Lat": 32.814018,
  "Lon": -96.948894
}, {
  "City": "Lubbock",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Lubbock,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Lubbock%2C_Texas.png/180px-Flag_of_Lubbock%2C_Texas.png",
  "Lat": 33.577863,
  "Lon": -101.855166
}, {
  "City": "Murphy",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Murphy,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Murphy%2C_Texas.png/180px-Flag_of_Murphy%2C_Texas.png",
  "Lat": 33.015121,
  "Lon": -96.613049
}, {
  "City": "Odessa",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Odessa,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Odessa%2C_Texas.png/180px-Flag_of_Odessa%2C_Texas.png",
  "Lat": 31.845682,
  "Lon": -102.367643
}, {
  "City": "Plano",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Plano,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Plano%2C_Texas.png/180px-Flag_of_Plano%2C_Texas.png",
  "Lat": 33.019843,
  "Lon": -96.698886
}, {
  "City": "Richardson",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Richardson,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Richardson%2C_Texas.png/180px-Flag_of_Richardson%2C_Texas.png",
  "Lat": 32.948333,
  "Lon": -96.729852
}, {
  "City": "Temple",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Temple,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Flag_of_Temple%2C_Texas.png/180px-Flag_of_Temple%2C_Texas.png",
  "Lat": 31.098234,
  "Lon": -97.342782
}, {
  "City": "Von Ormy",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/Von_Ormy,_Texas",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Flag_of_Von_Ormy%2C_Texas.png/180px-Flag_of_Von_Ormy%2C_Texas.png",
  "Lat": 29.288989,
  "Lon": -98.644785
}, {
  "City": "Mesa",
  "State": "Arizona",
  "Link": "//en.wikipedia.org/wiki/Mesa,_Arizona",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/4/40/Flag_of_Mesa%2C_Arizona.svg/180px-Flag_of_Mesa%2C_Arizona.svg.png",
  "Lat": 33.415184,
  "Lon": -111.831472
}, {
  "City": "Phoenix",
  "State": "Arizona",
  "Link": "//en.wikipedia.org/wiki/Phoenix,_Arizona",
  "Image": "//upload.wikimedia.org/wikipedia/en/thumb/9/98/Flag_of_Phoenix%2C_Arizona.svg/220px-Flag_of_Phoenix%2C_Arizona.svg.png",
  "Lat": 33.448377,
  "Lon": -112.074037
}, {
  "City": "Tucson",
  "State": "Arizona",
  "Link": "//en.wikipedia.org/wiki/Tucson,_Arizona",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Flag_of_Tucson%2C_Arizona.png/180px-Flag_of_Tucson%2C_Arizona.png",
  "Lat": 32.221743,
  "Lon": -110.926479
}, {
  "City": "Colorado Springs",
  "State": "Colorado",
  "Link": "//en.wikipedia.org/wiki/Colorado_Springs,_Colorado",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Colorado_Springs%2C_Colorado.svg/180px-Flag_of_Colorado_Springs%2C_Colorado.svg.png",
  "Lat": 38.833882,
  "Lon": -104.821363
}, {
  "City": "Denver",
  "State": "Colorado",
  "Link": "//en.wikipedia.org/wiki/Denver",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/61/Flag_of_Denver%2C_Colorado.svg/180px-Flag_of_Denver%2C_Colorado.svg.png",
  "Lat": 39.738436,
  "Lon": -104.984859
}, {
  "City": "Goldfield",
  "State": "Colorado",
  "Link": "//en.wikipedia.org/wiki/Goldfield,_Colorado",
  "Image": "//upload.wikimedia.org/wikipedia/en/thumb/5/52/Fag_of_Goldfield%2C_Colorado.jpg/180px-Fag_of_Goldfield%2C_Colorado.jpg",
  "Lat": 38.717767,
  "Lon": -105.126091
}, {
  "City": "Pueblo",
  "State": "Colorado",
  "Link": "//en.wikipedia.org/wiki/Pueblo,_Colorado",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Flag_of_Pueblo%2C_Colorado.gif/180px-Flag_of_Pueblo%2C_Colorado.gif",
  "Lat": 38.254447,
  "Lon": -104.609141
}, {
  "City": "Fort Collins",
  "State": "Colorado",
  "Link": "//en.wikipedia.org/wiki/Fort_Collins,_Colorado",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Flag_of_Fort_Collins%2C_Colorado.gif/180px-Flag_of_Fort_Collins%2C_Colorado.gif",
  "Lat": 40.58526,
  "Lon": -105.084423
}, {
  "City": "Westminster",
  "State": "Colorado",
  "Link": "//en.wikipedia.org/wiki/Westminster,_Colorado",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Westminster%2C_Colorado.gif/180px-Flag_of_Westminster%2C_Colorado.gif",
  "Lat": 39.836653,
  "Lon": -105.037205
}, {
  "City": "Billings",
  "State": "Montana",
  "Link": "//en.wikipedia.org/wiki/Billings,_Montana",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_placeholder.svg/180px-Flag_placeholder.svg.png",
  "Lat": 45.783286,
  "Lon": -108.50069
}, {
  "City": "Las Vegas",
  "State": "Nevada",
  "Link": "//en.wikipedia.org/wiki/Las_Vegas,_Nevada",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Las_Vegas%2C_Nevada.svg/180px-Flag_of_Las_Vegas%2C_Nevada.svg.png",
  "Lat": 36.169941,
  "Lon": -115.13983
}, {
  "City": "Reno",
  "State": "Nevada",
  "Link": "//en.wikipedia.org/wiki/Reno,_Nevada",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/1/14/Flag_of_Reno%2C_Nevada.svg/180px-Flag_of_Reno%2C_Nevada.svg.png",
  "Lat": 39.529633,
  "Lon": -119.813803
}, {
  "City": "Elko",
  "State": "Nevada",
  "Link": "//en.wikipedia.org/wiki/Elko,_Nevada",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Elko%2C_Nevada.gif/180px-Flag_of_Elko%2C_Nevada.gif",
  "Lat": 40.832421,
  "Lon": -115.763123
}, {
  "City": "Albuquerque",
  "State": "New Mexico",
  "Link": "//en.wikipedia.org/wiki/Albuquerque,_New_Mexico",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Albuquerque%2C_New_Mexico.svg/180px-Flag_of_Albuquerque%2C_New_Mexico.svg.png",
  "Lat": 35.110703,
  "Lon": -106.609991
}, {
  "City": "Roswell",
  "State": "New Mexico",
  "Link": "//en.wikipedia.org/wiki/Roswell,_New_Mexico",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Flag_of_Roswell%2C_New_Mexico.svg/180px-Flag_of_Roswell%2C_New_Mexico.svg.png",
  "Lat": 33.394266,
  "Lon": -104.523024
}, {
  "City": "Grand Forks",
  "State": "North Dakota",
  "Link": "//en.wikipedia.org/wiki/Grand_Forks,_North_Dakota",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_placeholder.svg/180px-Flag_placeholder.svg.png",
  "Lat": 47.925257,
  "Lon": -97.032855
}, {
  "City": "Provo",
  "State": "Utah",
  "Link": "//en.wikipedia.org/wiki/Provo,_Utah",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Flag_of_Provo%2C_Utah.svg/180px-Flag_of_Provo%2C_Utah.svg.png",
  "Lat": 40.233844,
  "Lon": -111.658534
}, {
  "City": "Salt Lake City",
  "State": "Utah",
  "Link": "//en.wikipedia.org/wiki/Salt_Lake_City,_Utah",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_placeholder.svg/180px-Flag_placeholder.svg.png",
  "Lat": 40.760779,
  "Lon": -111.891047
}, {
  "City": "Anaheim",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Anaheim,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Anaheim%2C_California.png/180px-Flag_of_Anaheim%2C_California.png",
  "Lat": 33.835293,
  "Lon": -117.914504
}, {
  "City": "Bakersfield",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Bakersfield,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/be/Flag_of_Bakersfield%2C_California.png/180px-Flag_of_Bakersfield%2C_California.png",
  "Lat": 35.373292,
  "Lon": -119.018712
}, {
  "City": "Beverly Hills",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Beverly_Hills,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Flag_of_Beverly_Hills%2C_California.png/180px-Flag_of_Beverly_Hills%2C_California.png",
  "Lat": 34.07362,
  "Lon": -118.400356
}, {
  "City": "Chula Vista",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Chula_Vista,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Flag_of_Chula_Vista%2C_California.svg/180px-Flag_of_Chula_Vista%2C_California.svg.png",
  "Lat": 32.640054,
  "Lon": -117.084196
}, {
  "City": "Coronado",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Coronado,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_Coronado%2C_California.svg/180px-Flag_of_Coronado%2C_California.svg.png",
  "Lat": 32.685885,
  "Lon": -117.183089
}, {
  "City": "Costa Mesa",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Costa_Mesa,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/76/Flag_of_Costa_Mesa%2C_California.png/180px-Flag_of_Costa_Mesa%2C_California.png",
  "Lat": 33.641132,
  "Lon": -117.918669
}, {
  "City": "Cupertino",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Cupertino,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/0/02/Flag_of_Cupertino%2C_California.svg/180px-Flag_of_Cupertino%2C_California.svg.png",
  "Lat": 37.322998,
  "Lon": -122.032182
}, {
  "City": "Downey",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Downey,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Flag_of_Downey%2C_California.svg/180px-Flag_of_Downey%2C_California.svg.png",
  "Lat": 33.940109,
  "Lon": -118.133159
}, {
  "City": "Escondido",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Escondido,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Escondido%2C_California.svg/180px-Flag_of_Escondido%2C_California.svg.png",
  "Lat": 33.119207,
  "Lon": -117.086421
}, {
  "City": "Fresno",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Fresno,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Fresno%2C_California.svg/180px-Flag_of_Fresno%2C_California.svg.png",
  "Lat": 36.746842,
  "Lon": -119.772587
}, {
  "City": "Garden Grove",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Garden_Grove,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_Garden_Grove%2C_California.png/180px-Flag_of_Garden_Grove%2C_California.png",
  "Lat": 33.773905,
  "Lon": -117.941448
}, {
  "City": "Gilroy",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Gilroy,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_Gilroy%2C_California.png/180px-Flag_of_Gilroy%2C_California.png",
  "Lat": 37.005782,
  "Lon": -121.568275
}, {
  "City": "Glendale",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Glendale,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Flag_of_Glendale%2C_California.png/180px-Flag_of_Glendale%2C_California.png",
  "Lat": 34.142508,
  "Lon": -118.255075
}, {
  "City": "Huntington Beach",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Huntington_Beach,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/2/24/Flag_of_Huntington_Beach%2C_California.svg/180px-Flag_of_Huntington_Beach%2C_California.svg.png",
  "Lat": 33.660297,
  "Lon": -117.999227
}, {
  "City": "Inglewood",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Inglewood,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Flag_of_Inglewood%2C_California.png/180px-Flag_of_Inglewood%2C_California.png",
  "Lat": 33.96168,
  "Lon": -118.353131
}, {
  "City": "La Mesa",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/La_Mesa,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Flag_of_La_Mesa%2C_California.png/180px-Flag_of_La_Mesa%2C_California.png",
  "Lat": 32.767829,
  "Lon": -117.023084
}, {
  "City": "Los Angeles",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Los_Angeles",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Los_Angeles%2C_California.svg/180px-Flag_of_Los_Angeles%2C_California.svg.png",
  "Lat": 34.052234,
  "Lon": -118.243685
}, {
  "City": "Los Gatos",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Los_Gatos,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Los_Gatos%2C_California.png/180px-Flag_of_Los_Gatos%2C_California.png",
  "Lat": 37.235808,
  "Lon": -121.962375
}, {
  "City": "Monterey",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Monterey,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Flag_of_Monterey%2C_California.svg/180px-Flag_of_Monterey%2C_California.svg.png",
  "Lat": 36.600238,
  "Lon": -121.894676
}, {
  "City": "Moreno Valley",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Moreno_Valley,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Moreno_Valley%2C_California.png/180px-Flag_of_Moreno_Valley%2C_California.png",
  "Lat": 33.942466,
  "Lon": -117.229672
}, {
  "City": "Morgan Hill",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Morgan_Hill,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Flag_of_Morgan_Hill%2C_California.svg/180px-Flag_of_Morgan_Hill%2C_California.svg.png",
  "Lat": 37.130501,
  "Lon": -121.65439
}, {
  "City": "Oakland",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Oakland,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Flag_of_Oakland%2C_California.svg/180px-Flag_of_Oakland%2C_California.svg.png",
  "Lat": 37.804364,
  "Lon": -122.271114
}, {
  "City": "Oceanside",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Oceanside,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_Oceanside%2C_California.png/180px-Flag_of_Oceanside%2C_California.png",
  "Lat": 33.19587,
  "Lon": -117.379483
}, {
  "City": "Pasadena",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Pasadena,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Flag_of_Pasadena%2C_California.png/180px-Flag_of_Pasadena%2C_California.png",
  "Lat": 34.147785,
  "Lon": -118.144516
}, {
  "City": "Pomona",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Pomona,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/69/Flag_of_Pomona%2C_California.png/180px-Flag_of_Pomona%2C_California.png",
  "Lat": 34.055103,
  "Lon": -117.749991
}, {
  "City": "Poway",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Poway,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Poway%2C_California.png/180px-Flag_of_Poway%2C_California.png",
  "Lat": 32.962823,
  "Lon": -117.035865
}, {
  "City": "Rancho Mirage",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Rancho_Mirage,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Flag_of_Rancho_Mirage%2C_California.png/180px-Flag_of_Rancho_Mirage%2C_California.png",
  "Lat": 33.739744,
  "Lon": -116.41279
}, {
  "City": "Redding",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Redding,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Redding%2C_California.png/180px-Flag_of_Redding%2C_California.png",
  "Lat": 40.58654,
  "Lon": -122.391675
}, {
  "City": "Riverside",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Riverside,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Flag_of_Riverside%2C_California.svg/180px-Flag_of_Riverside%2C_California.svg.png",
  "Lat": 33.953349,
  "Lon": -117.396156
}, {
  "City": "Sacramento",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Sacramento,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Flag_of_Sacramento%2C_California.svg/180px-Flag_of_Sacramento%2C_California.svg.png",
  "Lat": 38.581572,
  "Lon": -121.4944
}, {
  "City": "San Bernardino",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/San_Bernardino,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_San_Bernardino%2C_California.png/180px-Flag_of_San_Bernardino%2C_California.png",
  "Lat": 34.108345,
  "Lon": -117.289765
}, {
  "City": "San Diego",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/San_Diego",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_San_Diego%2C_California.svg/180px-Flag_of_San_Diego%2C_California.svg.png",
  "Lat": 32.715738,
  "Lon": -117.161084
}, {
  "City": "San Francisco",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/San_Francisco",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_San_Francisco.svg/180px-Flag_of_San_Francisco.svg.png",
  "Lat": 37.77493,
  "Lon": -122.419416
}, {
  "City": "San Jose",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/San_Jose,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/4/46/Flag_of_San_Jose%2C_California.png/180px-Flag_of_San_Jose%2C_California.png",
  "Lat": 37.333596,
  "Lon": -121.890704
}, {
  "City": "San Luis Obispo",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/San_Luis_Obispo,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_San_Luis_Obispo%2C_California.svg/180px-Flag_of_San_Luis_Obispo%2C_California.svg.png",
  "Lat": 35.282752,
  "Lon": -120.659616
}, {
  "City": "Santa Ana",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Santa_Ana,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Santa_Ana%2C_California.svg/180px-Flag_of_Santa_Ana%2C_California.svg.png",
  "Lat": 33.745573,
  "Lon": -117.867834
}, {
  "City": "Santa Barbara",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Santa_Barbara,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Santa_Barbara%2C_California.svg/180px-Flag_of_Santa_Barbara%2C_California.svg.png",
  "Lat": 34.420831,
  "Lon": -119.69819
}, {
  "City": "Santa Clara",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Santa_Clara,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Flag_of_Santa_Clara%2C_California.png/180px-Flag_of_Santa_Clara%2C_California.png",
  "Lat": 37.354108,
  "Lon": -121.955236
}, {
  "City": "Santa Clarita",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Santa_Clarita,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Santa_Clarita%2C_California.png/180px-Flag_of_Santa_Clarita%2C_California.png",
  "Lat": 34.391664,
  "Lon": -118.542586
}, {
  "City": "Sunnyvale",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Sunnyvale,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Sunnyvale%2C_California.png/180px-Flag_of_Sunnyvale%2C_California.png",
  "Lat": 37.36883,
  "Lon": -122.03635
}, {
  "City": "Torrance",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Torrance,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Torrance%2C_California.png/180px-Flag_of_Torrance%2C_California.png",
  "Lat": 33.835849,
  "Lon": -118.340629
}, {
  "City": "Watsonville",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Watsonville,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Flag_of_Watsonville%2C_California.png/180px-Flag_of_Watsonville%2C_California.png",
  "Lat": 36.910231,
  "Lon": -121.756895
}, {
  "City": "Woodland",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Woodland,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Flag_of_Woodland%2C_California.svg/180px-Flag_of_Woodland%2C_California.svg.png",
  "Lat": 38.678516,
  "Lon": -121.773297
}, {
  "City": "Portland",
  "State": "Oregon",
  "Link": "//en.wikipedia.org/wiki/Portland,_Oregon",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Portland%2C_Oregon.svg/180px-Flag_of_Portland%2C_Oregon.svg.png",
  "Lat": 45.523062,
  "Lon": -122.676482
}, {
  "City": "Anchorage",
  "State": "Alaska",
  "Link": "//en.wikipedia.org/wiki/Anchorage,_Alaska",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Anchorage%2C_Alaska.svg/180px-Flag_of_Anchorage%2C_Alaska.svg.png",
  "Lat": 61.218056,
  "Lon": -149.900278
}, {
  "City": "Juneau",
  "State": "Alaska",
  "Link": "//en.wikipedia.org/wiki/Juneau,_Alaska",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Juneau%2C_Alaska.svg/180px-Flag_of_Juneau%2C_Alaska.svg.png",
  "Lat": 58.301944,
  "Lon": -134.419722
}, {
  "City": "Honolulu",
  "State": "Hawaii",
  "Link": "//en.wikipedia.org/wiki/Honolulu",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Honolulu%2C_Hawaii.svg/180px-Flag_of_Honolulu%2C_Hawaii.svg.png",
  "Lat": 21.306944,
  "Lon": -157.858333
}, {
  "City": "Seattle",
  "State": "Washington",
  "Link": "//en.wikipedia.org/wiki/Seattle",
  "Image": "//upload.wikimedia.org/wikipedia/en/thumb/6/6d/Flag_of_Seattle.svg/190px-Flag_of_Seattle.svg.png",
  "Lat": 47.609722,
  "Lon": -122.333056
}, {
  "City": "San Antonio",
  "State": "Texas",
  "Link": "//en.wikipedia.org/wiki/San_Antonio",
  "Image": "//upload.wikimedia.org/wikipedia/en/thumb/2/2a/Flag_of_San_Antonio%2C_Texas.svg/220px-Flag_of_San_Antonio%2C_Texas.svg.png",
  "Lat": 29.416667,
  "Lon": -98.5
}, {
  "City": "Long Beach",
  "State": "California",
  "Link": "//en.wikipedia.org/wiki/Long_Beach,_California",
  "Image": "//upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Long_Beach_CA_flag.gif/200px-Long_Beach_CA_flag.gif",
  "Lat": 33.768333,
  "Lon": -118.195556
}, {
  "City": "Beloit",
  "State": "Wisconsin",
  "Link": "//en.wikipedia.org/wiki/Beloit,_Wisconsin",
  "Image": "//upload.wikimedia.org/wikipedia/en/thumb/8/88/BeloitFlag.jpg/220px-BeloitFlag.jpg",
  "Lat": 42.508333,
  "Lon": -89.031667
}]